name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
        uses: actions/checkout@v2   # 官方的action，获取代码

    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # 三方的action操作， 执行docker login
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3  # 抽取项目信息，主要是镜像的tag
      with:
        images: ufoe/mychat

    - name: Build and push Docker image
      uses: docker/build-push-action@v2 # docker build & push
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
